// src/components/ExportButtonGroup.tsx

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, FileText } from "lucide-react";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import { 
  Select, SelectTrigger, SelectValue, 
  SelectContent, SelectItem 
} from "@/components/ui/select";

// ✅ Import fonts (already generated by fontconverter.js)
import "@/assets/fonts/NotoSans-Regular.js";
import "@/assets/fonts/NotoSans-Bold.js";
import "@/assets/fonts/NotoSans-Italic.js";
import "@/assets/fonts/NotoSans-BoldItalic.js";

interface ExportButtonGroupProps {
  voiceUrl?: string;
  lyrics?: string;
}

const ExportButtonGroup: React.FC<ExportButtonGroupProps> = ({ voiceUrl, lyrics }) => {
  const [selectedFont, setSelectedFont] = useState("NotoSansRegular");
  const [fontSize, setFontSize] = useState(14);

  const handleExportText = () => {
    if (!lyrics) return;
    const blob = new Blob([lyrics], { type: "text/plain;charset=utf-8" });
    saveAs(blob, "translation.txt");
  };

  const handleExportAudio = () => {
    if (!voiceUrl) return;
    saveAs(voiceUrl, "translation.mp3");
  };

  const handleExportPDF = () => {
    if (!lyrics) return;
    const doc = new jsPDF();

    // ✅ Use chosen font and size
    doc.setFont(selectedFont, "normal");
    doc.setFontSize(18);
    doc.text("🌍 Live Translator Export", 20, 20);

    doc.setFontSize(12);
    doc.text("Translated Text:", 20, 40);

    doc.setFontSize(fontSize);
    doc.text(lyrics, 20, 55, { maxWidth: 170 });

    doc.save("translation.pdf");
  };

  return (
    <div className="flex flex-col gap-4 mt-4">
      {/* Controls */}
      <div className="flex flex-wrap gap-4 items-center">
        {/* Font Style */}
        <div className="flex items-center gap-2">
          <span className="text-sm text-gray-600">Font Style:</span>
          <Select onValueChange={setSelectedFont} defaultValue="NotoSansRegular">
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Select Font" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="NotoSansRegular">Regular</SelectItem>
              <SelectItem value="NotoSansBold">Bold</SelectItem>
              <SelectItem value="NotoSansItalic">Italic</SelectItem>
              <SelectItem value="NotoSansBoldItalic">Bold Italic</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Font Size */}
        <div className="flex items-center gap-2">
          <span className="text-sm text-gray-600">Font Size:</span>
          <Select onValueChange={(val) => setFontSize(Number(val))} defaultValue="14">
            <SelectTrigger className="w-[100px]">
              <SelectValue placeholder="Size" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="12">12</SelectItem>
              <SelectItem value="14">14</SelectItem>
              <SelectItem value="16">16</SelectItem>
              <SelectItem value="18">18</SelectItem>
              <SelectItem value="20">20</SelectItem>
              <SelectItem value="24">24</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Export Buttons */}
      <div className="flex flex-wrap gap-3">
        <Button onClick={handleExportText} variant="outline" disabled={!lyrics}>
          <Download className="w-4 h-4 mr-2" /> Export Text
        </Button>
        <Button onClick={handleExportAudio} variant="outline" disabled={!voiceUrl}>
          <Download className="w-4 h-4 mr-2" /> Export Audio
        </Button>
        <Button onClick={handleExportPDF} variant="outline" disabled={!lyrics}>
          <FileText className="w-4 h-4 mr-2" /> Export PDF
        </Button>
      </div>
    </div>
  );
};

export default ExportButtonGroup;